### ISSUE TITLE
heatmap plotting and batch effect correction

### ISSUE THREAD

**Issue by yxaxaxa** [shibiaowan/SHARP#4]
Dear author:
Thanks for providing such fast integration tools, I have just ended a 310k cell integration with only 10minutes, however, there were some questions about the usage of this packages:
1 when I try to build a heat map follow the tutorial
`plot_markers(sginfo),
`
 the message returned as follows

`Marker-genes heatmap saved into markers_heatmap.png`

However, I cannot find any file that ended with png, on all working directory
another command which help produce clustering result
`visualization_SHARP(res, label)  `
works fine
2.When I try to add scRNA data from different source e.g. merge 3 health controls with 4 multiple sclerosis, the final clustering result reveals a batch effect, that the newly formed cell cluster only contains either healthy or disease cell, would you mind give me some help so I can address these issues?

Best,

**Comment by shibiaowan** [comment]
Hi,

For the 1st question, you can try to explicitly give the output file name by filename

y = SHARP(scExp)
sginfo = get_marker_genes(scExp, y)
**outfile = "your_file_name.png"
sortmarker = plot_markers(sginfo, filename = outfile)**

For the 2nd question, please note that the current version of SHARP is unable to make batch correction. It is supposed to do clustering for those data in the same batch or the data that have been batch-corrected. We are in the process to develop a newer version of SHARP to propose RP-based batch correction method. For the current version, one solution is to use some other batch-correction methods and then use SHARP for clustering.

**Comment by yxaxaxa** [comment]
Thanks for your timely response,  looking forward to batch-correction version
